PUT http://localhost:3001/api/blogs/5f38a46f41fb1307610a3e8f
Content-Type: application/json

{
  "title": "Finished refactoring",
  "author": "Sevak",
  "url": "www.sevak.com/cpscReview",
  "likes": 55
}
